# Simple multilanguage support for English and Italian

from sqlite3 import DateFromTicks
from types import GenericAlias


LANGUAGES = {
    'en': {
        'app_title': 'Raspy Utility',
        'success': 'SUCCESS: {msg}',
        'error': 'ERROR: {msg}',
        'menu_file': '🗃 File',
        'menu_exit': '❌ Exit',
        'menu_log': '📊 Log',
        'menu_view_log': '👁️ View Log',
        'menu_help': '❓ Help',
        'menu_about': '📜 About',
        'menu_sponsor': '💰 Sponsor',
        'menu_version': 'Version',
        'menu_language': '🌐 Language',
        'menu_tools': '⚙️ Tools',
        'menu_view': '👁️ View',
        'menu_view_log': '📊 View Log',
        'menu_gpio': 'GPIO',
        'menu_settings': '⚙️ Settings',
        'log_viewer_title': 'Application Log',
        'close': 'Close',
        'log_file_not_found': 'Log file not found.',
        'no_log_entries': 'No log entries for {level}',
        'usage_tab': 'Usage',
        'features_tab': 'Features',
        'sponsor_on_github': 'Sponsor on GitHub',
        'join_discord': 'Join Discord',
        'buy_me_a_coffee': 'Paypal Donation',
        'join_the_patreon': 'Join the Patreon',
        'about_title': '📜 About',
        'about_project': 'Project',
        'about_description': 'A modern Python GUI app for demonstration and productivity.',
        'copyright': '\u00a9 2025 Nsfr750',
        'show_version': 'Show Version',
        'version_info': 'Version Information',
        'gpio_control': 'GPIO Control',
        'gpio_pin': 'Pin GPIO:',
        'gpio_on': 'On',
        'gpio_off': 'Off',
        'status': 'State',
        'log': 'Log',
        'disconnected': 'Disconnected',
        'gpio_turned_on': 'Pin GPIO {pin} On',
        'gpio_turned_off': 'Pin GPIO {pin} Off',
        'gpio_on_status': 'GPIO {pin} On',
        'gpio_off_status': 'GPIO {pin} Off',
        'connection_error': 'Connection Error',
        'gpio_simulator': 'GPIO Simulator',
        'gpio_start_simulator': 'Start Simulator',
        'gpio_stop_simulator': 'Stop Simulator',
        'gpio_simulator_started': 'GPIO Simulator started on port 5000',
        'gpio_simulator_stopped': 'GPIO Simulator stopped',
        'error_starting_simulator': 'Error starting simulator',
        'error_stopping_simulator': 'Error stopping simulator',
        'help_usage': "To start the application, run main.py from the project root.\nNavigate the menu bar for Help, About, Log Viewer, and more.\nUse the Log Viewer to see and filter application logs in real time.\nCustom log entries can be added in your code using log_info, log_warning, log_error.\nCommon troubleshooting: If you see import errors, ensure you are running from the root directory.\n",
        'help_features': "- Centralized logging system: info, warning, error, and uncaught exceptions are logged to traceback.log.\n- Log Viewer dialog with real-time filtering: view ALL, INFO, WARNING, or ERROR entries.\n- Use log_info, log_warning, log_error for custom log entries in your code.\n- Robust error handling and extensible design.\n",
        'settings': 'Settings',
        'settings_title': 'Application Settings',
        'shortcuts_tab': 'Shortcuts',
        'welcome_tab': 'Welcome',
        'help_title': 'Help',
        'gpio_settings': 'GPIO Settings',
        'remote_gpio_settings': 'Remote GPIO',
        'local_gpio_settings': 'Local GPIO',
        'enable_remote_gpio': 'Enable Remote GPIO',
        'host': 'Host',
        'api_key': 'API Key',
        'show_api_key': 'Show',
        'gpio_mode': 'GPIO Mode',
        'save': 'Save',
        'cancel': 'Cancel',
        'settings_saved': 'Settings Saved',
        'settings_saved_message': 'The settings have been saved successfully.',
        'error_saving_settings': 'Error saving settings: {error}',
        'host_required': 'Host is required when remote GPIO is enabled.',
        'support_message': 'If you find this project useful, consider sponsoring it on Patreon or GitHub.',
        'sponsor': 'Sponsor',
        'about': 'Info',
        'select_pin': 'PIN Selection',
        'direction': 'Direction',
        'initial_state': 'Initial State',
        'setup_gpio': 'GPIO Setup',
        'gpio_not_initialized': 'GPIO Not Initialized',
        'general': 'General',
        'network': 'LAN',
        'appearance': 'Appearance',
        'theme': 'Theme',
        'light': 'Lighr',
        'dark': 'Dark',
        'system': 'System',
        'language': 'Language',
        'en': 'English',
        'it': 'Italian',
        'led_pin': 'LED Pin',
        'button_pin': 'Pin Button',
        'remote_gpio': 'Remote GPIO',
        'remote_host': 'Remote Host',
        'server_host': 'Server Host',
        'server_port': 'Server Port',
        'start_minimized': 'Start Minimized',
        'check_updates': 'Check Updates',
        'check_updates_on_startup': 'Check Ipdates on Startup',
        'help_title': 'Help',
        'gpio_title': 'GPIO',
        'log_title': 'Log',
    },
    'it': {
        'app_title': 'Raspy Utility',
        'success': 'SUCCESSO: {msg}',
        'error': 'ERRORE: {msg}',
        'menu_file': '🗃 File',
        'menu_exit': '❌ Esci',
        'menu_log': '📊 Log',
        'view_log': '👁️ Visualizza Log',
        'menu_help': '❓ Aiuto',
        'menu_about': '📜 Informazioni',
        'menu_sponsor': '💰 Supporta',
        'menu_version': 'Versione',
        'menu_language': '🌐 Lingua',
        'menu_tools': '⚙️ Tools',
        'menu_view': '👁️ Visualizza',
        'menu_view_log': '📊 Visualizza Log',
        'menu_gpio': 'GPIO',
        'menu_settings': '⚙️ Impostazioni',
        'log_viewer_title': 'Log Applicazione',
        'close': 'Chiudi',
        'log_file_not_found': 'File di log non trovato.',
        'no_log_entries': 'Nessuna voce di log per {level}',
        'usage_tab': 'Utilizzo',
        'features_tab': 'Caratteristiche',
        'sponsor_on_github': 'Supporta su GitHub',
        'join_discord': 'Unisciti a Discord',
        'buy_me_a_coffee': 'Donazione con Paypal',
        'join_the_patreon': 'Unisciti a Patreon',
        'about_title': 'Informazioni',
        'about_project': 'Progetto',
        'about_description': 'Un\'applicazione GUI Python moderna per dimostrazione e produttività.',
        'copyright': '\u00a9 2025 Nsfr750',
        'show_version': 'Mostra Versione',
        'version_info': 'Informazioni Versione',
        'gpio_control': 'Controllo GPIO',
        'gpio_pin': 'Pin GPIO:',
        'gpio_on': 'Acceso',
        'gpio_off': 'Spento',
        'status': 'Stato',
        'log': 'Log',
        'disconnected': 'Disconnesso',
        'gpio_turned_on': 'Pin GPIO {pin} acceso',
        'gpio_turned_off': 'Pin GPIO {pin} spento',
        'gpio_on_status': 'GPIO {pin} acceso',
        'gpio_off_status': 'GPIO {pin} spento',
        'connection_error': 'Errore di connessione',
        'gpio_simulator': 'Simulatore GPIO',
        'gpio_start_simulator': 'Avvia Simulatore',
        'gpio_stop_simulator': 'Ferma Simulatore',
        'gpio_simulator_started': 'Simulatore GPIO avviato sulla porta 5000',
        'gpio_simulator_stopped': 'Simulatore GPIO fermato',
        'error_starting_simulator': 'Errore nell\'avvio del simulatore',
        'error_stopping_simulator': 'Errore durante l\'arresto del simulatore',
        'test_api': 'Test API',
        'test_api_running': 'Esecuzione test API in corso...',
        'test_api_success': 'Test API completati con successo',
        'test_api_error': 'Errore durante l\'esecuzione dei test API',
        'help_usage': "Per avviare l'applicazione, esegui main.py dalla directory principale.\nNaviga la barra dei menu per Aiuto, Informazioni, Visualizzatore Log e altro.\nUsa il Visualizzatore Log per vedere e filtrare i log dell'applicazione in tempo reale.\nPuoi aggiungere voci di log personalizzate nel tuo codice usando log_info, log_warning, log_error.\nRisoluzione problemi comuni: Se vedi errori di importazione, assicurati di eseguire dalla directory principale.\n",
        'help_features': "- Sistema di logging centralizzato: info, avvisi, errori ed eccezioni non gestite vengono registrati in traceback.log.\n- Finestra di visualizzazione log con filtraggio in tempo reale: visualizza voci TUTTE, INFO, AVVISI o ERRORI.\n- Usa log_info, log_warning, log_error per aggiungere voci di log personalizzate nel tuo codice.\n- Gestione degli errori robusta e design estensibile.\n- Interfaccia di controllo GPIO per Raspberry Pi.\n",
        'settings': 'Impostazioni',
        'settings_title': 'Impostazioni Applicazione',
        'shortcuts_tab': 'Scorciatoie',
        'welcome_tab': 'Benvenuti',
        'help_tab': 'Aiuto',
        'gpio_settings': 'Impostazioni GPIO',
        'remote_gpio_settings': 'GPIO Remoto',
        'local_gpio_settings': 'GPIO Locale',
        'enable_remote_gpio': 'Abilita GPIO Remoto',
        'host': 'Host',
        'api_key': 'Chiave API',
        'show_api_key': 'Mostra',
        'gpio_mode': 'Modalità GPIO',
        'save': 'Salva',
        'cancel': 'Annulla',
        'settings_saved': 'Impostazioni Salvate',
        'settings_saved_message': 'Le impostazioni sono state salvate con successo.',
        'error_saving_settings': 'Errore durante il salvataggio delle impostazioni: {error}',
        'host_required': 'È necessario specificare un host quando il GPIO remoto è abilitato.',
        'support_message': 'Se hai trovato questo progetto utile, considera di sponsorizzarlo su Patreon o GitHub.',
        'sponsor': 'Sponsorizza',
        'about': 'Informazioni',
        'select_pin': 'Selezione PIN',
        'direction': 'Direzione',
        'initial_state': 'Stato Iniziale',
        'setup_gpio': 'Setup GPIO',
        'gpio_not_initialized': 'GPIO non Inizializzato',
        'general': 'Generale',
        'network': 'Rete',
        'appearance': 'Aspetto',
        'theme': 'Tema',
        'light': 'Chiaro',
        'dark': 'Scuro',
        'system': 'Sistema',
        'language': 'Lingua',
        'en': 'Inglese',
        'it': 'Italiano',
        'led_pin': 'LED Pin',
        'button_pin': 'Pulsante Pin',
        'remote_gpio': 'GPIO Remoto',
        'remote_host': 'Host Remoto',
        'server_host': 'Host Server',
        'server_port': 'Porta Server',
        'start_minimized': 'Avvia Minimizzato',
        'check_updates': 'Controlla Aggiornamenti',
        'check_updates_on_startup': 'Controlla Aggiornamenti al Avvio',
        'help_title': 'Aiuto',
        'gpio_title': 'GPIO',
        'log_title': 'Log',
    }
}

import os
import json

CONFIG_PATH = os.path.join(os.path.dirname(__file__), 'config.json')

def _load_lang():
    try:
        with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
            data = json.load(f)
            return data.get('language', 'en')
    except Exception:
        return 'en'

def _save_lang(lang):
    try:
        with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
            json.dump({'language': lang}, f)
    except Exception:
        pass

_current_lang = _load_lang()

def set_language(lang):
    global _current_lang
    if lang in LANGUAGES:
        _current_lang = lang
    else:
        _current_lang = 'en'
    _save_lang(_current_lang)

def get_language():
    return _current_lang

def tr(key, **kwargs):
    text = LANGUAGES.get(_current_lang, LANGUAGES['en']).get(key, key)
    return text.format(**kwargs)
